### ISSUE TITLE
Script not working with Python3.12

### ISSUE THREAD

**Issue by bone6000** [bb-Ricardo/netbox-sync#391]
I've compiled the script successfully with python3.12.3 but when trying to run it I get this error messages:

[user01@test-machine]$ sudo /opt/netbox-sync/.venv/bin/python3 /opt/netbox-sync/netbox-sync.py
Traceback (most recent call last):
  File "/opt/netbox-sync/netbox-sync.py", line 24, in <module>
    from module.sources import instantiate_sources
  File "/opt/netbox-sync/module/sources/__init__.py", line 11, in <module>
    from module.sources.vmware.connection import VMWareHandler
  File "/opt/netbox-sync/module/sources/vmware/connection.py", line 23, in <module>
    from pyVim import connect
  File "/opt/netbox-sync/.venv/lib/python3.12/site-packages/pyVim/connect.py", line 37, in <module>
    from pyVmomi import vim, vmodl, SoapStubAdapter, SessionOrientedStub
  File "/opt/netbox-sync/.venv/lib/python3.12/site-packages/pyVmomi/__init__.py", line 39, in <module>
    from pyVmomi.SoapAdapter import SoapStubAdapter, StubAdapterBase, SoapCmdStubAdapter, \
  File "/opt/netbox-sync/.venv/lib/python3.12/site-packages/pyVmomi/SoapAdapter.py", line 1003, in <module>
    _SocketWrapper = ssl.wrap_socket
                     ^^^^^^^^^^^^^^^
AttributeError: module 'ssl' has no attribute 'wrap_socket'

The python3 version have the ssl module correct, but I think there is a change in the 3.12 version...

**Comment by bb-Ricardo** [comment]
Hi, Python 3.12 is not support. Only Python 3.11 as the underlying vmware SDK does not work well with Python 3.12

**Comment by bone6000** [comment]
OK Ricardo, thanks for your quick answer
